{"name": "test_2_element_not_interactable_exception_handling", "status": "passed", "start": 1710573196588, "stop": 1710573201821, "uuid": "febfbb2d-04f2-4c7a-9907-1b06eedae4f5", "historyId": "9a6e34206418c76e720e137facaa608f", "testCaseId": "9a6e34206418c76e720e137facaa608f", "fullName": "Tests.test_exception.TestLogin#test_2_element_not_interactable_exception_handling", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_exception"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-UEVTOM8"}, {"name": "thread", "value": "4100-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_exception"}]}