{"name": "test_verify_error_notification_with_invalid_username", "status": "passed", "start": 1709472780635, "stop": 1709472781181, "uuid": "dcff6103-543f-4fe3-ac95-22a232308f30", "historyId": "d5434eaee24d301aa8d9d029d1edcc34", "testCaseId": "d5434eaee24d301aa8d9d029d1edcc34", "fullName": "Tests.test_login.TestSearch#test_verify_error_notification_with_invalid_username", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestSearch"}, {"name": "host", "value": "DESKTOP-UEVTOM8"}, {"name": "thread", "value": "18348-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_login"}]}