{"name": "test_2_element_not_interactable_exception_handling", "status": "passed", "start": 1710526111352, "stop": 1710526116983, "uuid": "86a91023-3e50-485b-8696-9f7fda0e9a3e", "historyId": "9a6e34206418c76e720e137facaa608f", "testCaseId": "9a6e34206418c76e720e137facaa608f", "fullName": "Tests.test_exception.TestLogin#test_2_element_not_interactable_exception_handling", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_exception"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-UEVTOM8"}, {"name": "thread", "value": "10492-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_exception"}]}