{"name": "test_verify_error_notification_without_credentials", "status": "passed", "start": 1709527097714, "stop": 1709527098475, "uuid": "d828ae88-cc7a-4c80-adf1-2b6e42c8f337", "historyId": "a945018fb17d062f67219b9214f08baf", "testCaseId": "a945018fb17d062f67219b9214f08baf", "fullName": "Tests.test_login.TestLogin#test_verify_error_notification_without_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-UEVTOM8"}, {"name": "thread", "value": "23820-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_login"}]}