{"name": "test_1_no_such_element_exception_handling", "status": "passed", "start": 1710573180541, "stop": 1710573185716, "uuid": "fbaddeae-8d9d-461a-a742-32674fb04a60", "historyId": "ee3deca2b820bae813a122351c12a11e", "testCaseId": "ee3deca2b820bae813a122351c12a11e", "fullName": "Tests.test_exception.TestLogin#test_1_no_such_element_exception_handling", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_exception"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-UEVTOM8"}, {"name": "thread", "value": "4100-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_exception"}]}