{"name": "test6_verify_error_notification_without_credentials", "status": "passed", "start": 1710526219978, "stop": 1710526220131, "uuid": "98b39f35-64d2-4503-8090-a2e926451a89", "historyId": "4a4759846ac445ccc3ca9b12d5490ec9", "testCaseId": "4a4759846ac445ccc3ca9b12d5490ec9", "fullName": "Tests.test_login.TestLogin#test6_verify_error_notification_without_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-UEVTOM8"}, {"name": "thread", "value": "10492-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_login"}]}