{"name": "test4_verify_error_notification_with_invalid_password", "status": "passed", "start": 1710525291639, "stop": 1710525292045, "uuid": "a022f144-2227-4fe8-afed-2d856ca201d4", "historyId": "d8ed13f247a4d1fe92534b29a4c7af51", "testCaseId": "d8ed13f247a4d1fe92534b29a4c7af51", "fullName": "Tests.test_login.TestLogin#test4_verify_error_notification_with_invalid_password", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-UEVTOM8"}, {"name": "thread", "value": "5224-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_login"}]}