{"name": "test_1_no_such_element_exception_handling", "status": "passed", "start": 1710526094558, "stop": 1710526099962, "uuid": "6347e3ee-3846-46ab-94ed-bc6a1c50887a", "historyId": "ee3deca2b820bae813a122351c12a11e", "testCaseId": "ee3deca2b820bae813a122351c12a11e", "fullName": "Tests.test_exception.TestLogin#test_1_no_such_element_exception_handling", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_exception"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-UEVTOM8"}, {"name": "thread", "value": "10492-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_exception"}]}