{"name": "test_1_no_such_element_exception_handling", "status": "passed", "start": 1709527101884, "stop": 1709527107338, "uuid": "59e796dd-5ca8-4769-aaa9-484008899fba", "historyId": "ee3deca2b820bae813a122351c12a11e", "testCaseId": "ee3deca2b820bae813a122351c12a11e", "fullName": "Tests.test_exception.TestLogin#test_1_no_such_element_exception_handling", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_exception"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-UEVTOM8"}, {"name": "thread", "value": "23928-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_exception"}]}